# This is a sample .blackfire.yaml file created by Blackfire.
# You can read more about .blackfire.yaml here: https://blackfire.io/docs/cookbooks/tests
tests:
    "The homepage should be fast":
        path: "/"
        assertions:
            - "main.wall_time < 200ms"

# For writing scenarios, take a look at the documentation
# https://blackfire.io/docs/cookbooks/scenarios
scenarios: |
    #!blackfire-player

    scenario
        name 'The homepage should answer with a 200 status code'

       visit url('/')
           expect status_code() == 200
